### ISSUE TITLE
Eloquent date attributes are still of type Illuminate\Support\Carbon

### ISSUE THREAD

**Issue by Briareos17** [Propaganistas/Laravel-Intl#19]
I am trying to make alias for default carbon using service container but have dificults:
```
    use Illuminate\Support\Carbon;
    use Propaganistas\LaravelIntl\Facades\Carbon as IntlCarbon;

    $this->app->alias(IntlCarbon::class, Carbon::class);
```

But calling `$feedback->created_at->toShortDatetimeString()` returns me 

> Method toShortDatetimeString does not exist

**Comment by Propaganistas** [comment]
Eloquent's date attributes aren't built using the container; they're hardcoded to return an `Illuminate\Support\Carbon` instance. You could override the following methods to use `Propaganistas\LaravelIntl\Facades\Carbon` instead:
* [freshTimestamp()](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Concerns/HasTimestamps.php#L82)
* [asDateTime()](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L712)
