### ISSUE TITLE
Error when i try to use it

### ISSUE THREAD

**Issue by e2mkraft** [Propaganistas/Laravel-Intl#2]
When i try to use it Country::all(); i get error:
Call to undefined method CommerceGuys\Intl\Country\CountryRepository::setDefaultLocale()

**Comment by Propaganistas** [comment]
The current version of `commerceguys/intl` is in awaitance of a minor PR that this package needs to function correctly. As a temporary workaround this package should pull in my fork as specified in the composer.json file. Yet it seems that you've installed the "real" repo.

Could you please check if the method `setDefaultLocale()` is present in the following file?
`vendor/commerceguys/intl/src/LocaleResolverTrait.php`

**Comment by e2mkraft** [comment]
No that method not found there. What i need change to get it working? I installed it vai command composer require propaganistas/laravel-intl

ps. sorry my poor english :)

**Comment by Propaganistas** [comment]
That's odd..
Well, putting this inside your composer.json will definitely pull in the forked repo.

```json
"repositories": [
     {
         "type": "vcs",
         "url": "https://github.com/Propaganistas/intl"
     }
],
```

**Comment by e2mkraft** [comment]
Thanks, that solves my problem

**Comment by Propaganistas** [comment]
@e2mkraft In the meantime the PR I mentioned has been accepted. Please update to `1.1.3` to directly make use of the original `intl` repository.

**Comment by 0l1v3r5** [comment]
> ```json
> https://github.com/Propaganistas/intl
> ```



> That's odd..
> Well, putting this inside your composer.json will definitely pull in the forked repo.
> 
> ```json
> "repositories": [
>      {
>          "type": "vcs",
>          "url": "https://github.com/Propaganistas/intl"
>      }
> ],
> ```
> 
> Also run `composer update` afterwards

``` https://github.com/Propaganistas/Laravel-Intl``` instead of ``` https://github.com/Propaganistas/intl```
