### ISSUE TITLE
Incorrect annotation

### ISSUE THREAD

**Issue by LiborStransky** [Propaganistas/Laravel-Intl#22]
Hi, 
I would assume the annotation should be `string|null $number`
https://github.com/Propaganistas/Laravel-Intl/blob/645a34430ae92d287e97a06815d613be1f3002b5/src/helpers.php#L83

**Comment by Propaganistas** [comment]
Thanks for reporting.

https://github.com/Propaganistas/Laravel-Intl/commit/eb9412eaae023e3cdf3405f66cd05e2fa3dfdb81
