### ISSUE TITLE
Add support for Laravel 5.7?

### ISSUE THREAD

**Issue by skatetdieu** [Propaganistas/Laravel-Intl#24]
5.7 was just released but it won't install because this library doesn't support it. Per [this pull request](https://github.com/Propaganistas/Laravel-Intl/pull/23) it should just work.

**Comment by Propaganistas** [comment]
New release: https://github.com/Propaganistas/Laravel-Intl/releases/tag/2.1.1

Take a look at the release notes to check if the breaking change affects you.

**Comment by skatetdieu** [comment]
Thanks! All looks good!
