### ISSUE TITLE
Requires 'laravel/framework' really necessary?

### ISSUE THREAD

**Issue by bencarey-eman** [Propaganistas/Laravel-Intl#8]
I would quite like to implement this library into my Lumen based project, however, when I install it, it removes all of the individual `illuminate/*' libraries I have added, and installs the whole of Laravel, which, in turn, breaks my project.

Is it possible to amend the composer.json to not require Laravel? Maybe just require the individual illuminate libraries it requires? Or, alternatively, create a form specifically for Lumen? I am happy to do this but would rather it was done by the author of course :-)

**Comment by Propaganistas** [comment]
Could you please checkout the `lumen` branch and test thoroughly? Just to see if there are other issues/errors in Lumen after substituting the `laravel/framework` dependency.

**Comment by bencarey-eman** [comment]
I have loaded that dev-lumen branch and for the minimal functionality I require the library for, it works perfectly. To test it thoroughly will take me some time but as far as I can see, it works brilliantly!

Thank you very much!!

**Comment by Propaganistas** [comment]
I've tagged a new release (1.2.2).
